version = 0.1
[default.deploy.parameters]
stack_name = "chromoda-test"
resolve_s3 = true
s3_prefix = "chromoda-test"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
