GET https://v9d5jpgnsf.execute-api.us-east-1.amazonaws.com/dev/checkOrderState?
    order_id=61829745123
Accept: application/json

###
GET https://v9d5jpgnsf.execute-api.us-east-1.amazonaws.com/dev/checkOrderState?
    print_id=125153
Accept: application/json

###
POST https://v9d5jpgnsf.execute-api.us-east-1.amazonaws.com/dev/saveOrder?
    print_id=8012313&
    order_id=n%2Fa&
    tl_lon=-133.352&
    tl_lat=60.6642&
    tr_lon=-63.747&
    tr_lat=60.6642&
    bl_lon=-133.352&
    bl_lat=29.0978&
    br_lon=-63.747&
    br_lat=29.0978&
    color_a=%23FFFFFF&
    color_b=%230000FF&
    gradient=false&
    secondary=true&
    locationIcon=0&
    locationColor=%23FFFFFF&
    location_x=0.5&
    location_y=0.5
Content-Type: application/json

{}

###
POST https://v9d5jpgnsf.execute-api.us-east-1.amazonaws.com/dev/saveOrder?
    print_id=51151&
    order_id=n%2Fa&
    tl_lon=-133.35291188652573&
    tl_lat=60.664299833384035&
    tr_lon=-63.74708811347399&
    tr_lat=60.664299833384035&
    bl_lon=-133.35291188652573&
    bl_lat=29.097811690657053&
    br_lon=-63.74708811347399&
    br_lat=29.097811690657053&
    color_a=%23FFFFFF&
    color_b=%230000FF&
    gradient=false&
    secondary=true&
    locationIcon=0&
    locationColor=%23FFFFFF&
    location_x=null&
    location_y=null

Content-Type: application/json

{}

###
POST https://v9d5jpgnsf.execute-api.us-east-1.amazonaws.com/dev/saveOrder?
    print_id=57&
    order_id=125153&
    tl_lon=-94.9213&
    tl_lat=49.4823&
    tr_lon=-73.7544&
    tr_lat=49.4822&
    bl_lon=-94.9214&
    bl_lat=39.4275&
    br_lon=-73.7545&
    br_lat=39.4274&
    color_a=FFFFFF&
    color_b=FF0000&
    gradient=true&
    secondary=true&
    locationIcon=HEART&
    locationColor=FF0000&
    location_x=0.5&
    location_y=0.5

Content-Type: application/json

###
###
GET https://v9d5jpgnsf.execute-api.us-east-1.amazonaws.com/dev/generateTopo?
    tl_lon=-94.9213&tl_lat=49.4823&tr_lon=-73.7544&tr_lat=49.4822&bl_lon=-94.9214&bl_lat=39.4275&br_lon=-73.7545&
    br_lat=39.4274&lines=25&lines=25&width=1000
Accept: application/json

<> 2023-09-15T160704.502.json



